### PR TITLE
interactive learning changes

### PR DESCRIPTION
**Pull request by sidaw**
basically everything since july 2016. just for you to see as request, not intended to be merged.

### CODE REVIEW

**Comment by percyliang** [comment]
Can you merge master into your branch so it's easier to see the actual
diffs?

**Comment by sidaw** [comment]
Hmm. I did merge master into my branch, so I do not think any new master
commits shows up in the PR.
I see a bunch of Ice's commits from 2016/04 in the PR, and the problem
there seems to be that i merged a bunch of stuff from develop into my
branch, but those commits are not in master?
Should I PR to develop instead?

**Comment by percyliang** [comment]
For now, just for viewing, I'd submit the PR to develop so that the diffs are easy to see.

@ppasupat What's develop and can we merge it into master?

**Comment by ppasupat** [comment]
The develop branch contains my DPD / fictitious tables code and other scripts used in the ACL 2016 paper. Unfortunately it breaks the ACL 2015 tables system (i.e.,  much lower accuracy) and I couldn't get it to work. Would it be OK if I rename the branch to something else?

**Comment by percyliang** [comment]
Does this branch contain other useful improvements that we want to
maintain?  If so, then we should merge it.  We should tag a branch
spurious-acl2015 (should be the same version used in CodaLab), so people
who want to reproduce the results of that paper can always do it.

If we want to do interactive language learning with WikiTableQuestions
(Sida's stuff + yours), then it seems like we'll need both branches merged
into master.

**Comment by ppasupat** [comment]
I see. Let's merge develop into master (I will make a new pull request). I will tag the current master if someone wants to reproduce the ACL2015 tables result.

**Pull request closed without merging**
